config/routes.rb
Rails.application.routes.draw do
	resources :tweets do
		collection do
			get 'get_user_tweets'
		end
	end

	resources :profiles

	devise_for :users

	resources :home do
		collection do
			get 'search_user'
			get 'tweets'
		end
	end

	resources :following do
		collection do
			get 'follow'
			get 'unfollow'
			get 'following_list'
			get 'followers'
		end
	end

	resources :likes do
		collection do
			get 'like'
			get 'dislike'
		end
	end

	resources :comments do
		collection do
			post 'create_comment'
		end
	end

	devise_scope :user do
		authenticated :user do
			root to: "home#index", as: :authenticated_root
		end
		unauthenticated do
			root 'devise/sessions#new', as: :unauthenticated_root
		end
	end	

  match '/*a', to: 'application#not_found', via: [:get, :post, :put, :delete]
end

app/models/profile.rb
class Profile < ApplicationRecord
	mount_uploader :profile_image, AttachmentUploader
	validates :first_name, :last_name, :about_me, :user_id, presence: true
	belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :profile_exist?
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = current_user.profile
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @following_user = @profile.user
    @total_following = Following.where(user_id: current_user.id, is_following: true)
    @total_followers = Following.where(following_user_id: current_user.id, is_following: true)
    @following_size = @total_following.size
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :about_me, :date_of_birth, :profile_image, :user_id)
    end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="email">First name:</label>    
    <%= form.text_field :first_name, id: :profile_first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="email">Last name:</label>
    <%= form.text_field :last_name, id: :profile_last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="email">About me:</label>
    <%= form.text_area :about_me, id: :profile_about_me, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="email">Date of birth:</label>
    <%= form.date_select :date_of_birth, id: :profile_date_of_birth, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="email">Profile image:</label>
    <%= form.file_field :profile_image, id: :profile_profile_image, accept: "image/*" %>
  </div>

  <div class="field">    
    <%= form.hidden_field :user_id, value: current_user.id, id: :profile_user_id %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h3 align="center">Editing Profile</h3>

<%= render 'form', profile: @profile %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h3 align="center">Profiles</h3>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>About me</th>
      <th>Date of birth</th>
      <th>Profile image</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.about_me %></td>
        <td><%= profile.date_of_birth %></td>
        <td><%= profile.profile_image %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <% if can? :edit, profile %>
          <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <% end %>
        <% if can? :destroy, profile %>
          <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h3 align="center">Add Profile</h3>

<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<div align="">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-md-8 col-md-offset-1">
      <p style="float: right !important;"><%= link_to "Tweets", get_user_tweets_tweets_path(user_id: @profile.user_id) %></p>
      <div class="row">
        <div class="col-md-4">
          <%= image_tag(@profile.profile_image_url, size: "140x110", class: "img-rounded") unless @profile.profile_image_url.nil? %> 
        </div>
        <div class="col-md-4" align="right" id="follow-unfollow_id_<%= @profile.user.id%>">
          <% unless @following_user.id == current_user.id %>
            <% if is_following(@following_user.id) %>
              <div class= "t-pointer" onclick="followFunction(<%= @following_user.id %>)">Follow</div>
            <% else %>
              <div class= "t-pointer" onclick="unFollowFunction(<%= @following_user.id %>)">Unfollow</div>
            <% end %>
          <% else %>
            <p>Following - <%= link_to "#{@following_size}", following_list_following_index_path %></p>
            <p>Followers - <%= link_to "#{@total_followers.size}", followers_following_index_path(user_id: @profile.user_id) %></p>
          <% end %>          
        </div>
      </div><br>

      <table class="table table-striped">    
        <tbody align="">
          <tr>
            <td><strong>First name:</strong> <%= @profile.first_name %></td>        
          </tr>
           <tr>
            <td><strong>Last name:</strong> <%= @profile.last_name %></td>        
          </tr>
           <tr>
            <td><strong>About me:</strong> <%= @profile.about_me %></td>        
          </tr>
           <tr>
            <td><strong>Date of birth:</strong> <%= @profile.date_of_birth %></td>        
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% if can? :edit, @profile %>
  <%= link_to 'Edit', edit_profile_path(@profile) unless params[:tag]%>
<% end %>

<script type="text/javascript">
  function followFunction(user) {
    $.ajax({
      url: "<%= follow_following_index_path%>",
      data: {"following_user_id": user},
      success: function(data){
        $("#follow-unfollow_id_" + user).html('<div class= "t-pointer" onclick="unFollowFunction(' + user + ')">Unfollow</div>')
      }
    });
  }

  function unFollowFunction(user) {
    $.ajax({
      url: "<%= unfollow_following_index_path%>",
      data: {"following_user_id": user},
      success: function(data){
        $("#follow-unfollow_id_" + user).html('<div class= "t-pointer" onclick="followFunction(' + user + ')">Follow</div>')
      }
    });
  }
</script>