config/routes.rb
Rails.application.routes.draw do
	resources :tweets do
		collection do
			get 'get_user_tweets'
		end
	end

	resources :profiles

	devise_for :users

	resources :home do
		collection do
			get 'search_user'
			get 'tweets'
		end
	end

	resources :following do
		collection do
			get 'follow'
			get 'unfollow'
			get 'following_list'
			get 'followers'
		end
	end

	resources :likes do
		collection do
			get 'like'
			get 'dislike'
		end
	end

	resources :comments do
		collection do
			post 'create_comment'
		end
	end

	devise_scope :user do
		authenticated :user do
			root to: "home#index", as: :authenticated_root
		end
		unauthenticated do
			root 'devise/sessions#new', as: :unauthenticated_root
		end
	end	

  match '/*a', to: 'application#not_found', via: [:get, :post, :put, :delete]
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader
	validates :message, :user_id, presence: true
	validates_length_of :message, maximum: 280, allow_blank: true
	belongs_to :user
	has_many :likes
	has_many :comments
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /tweets
  # GET /tweets.json
  def index    
    @tweets = current_user.tweets
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @total_liked = @tweet.likes(is_like: true)
    @total_comments = @tweet.comments
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_user_tweets
    user = User.find(params[:user_id])
    @tweets =  user.tweets
    render file: "tweets/index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
    params.require(:tweet).permit(:message, :attachment, :user_id, :is_retweet, :current_tweet_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="message">Message Text:</label>    
    <%= form.text_area :message, id: :tweet_message, class: "form-control", size: "10x5", maxlength: 280 %>
  </div>

  <div class="form-group">
    <label for="attachment">Attachment:</label>
    <%= form.file_field :attachment, id: :tweet_attachment, accept: "image/*" %>
  </div>

  <div class="field">    
    <%= form.hidden_field :user_id, value: current_user.id, id: :tweet_user_id %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-default"%>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h3 align="center">Editing Tweet</h3>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h3 align="center">My Tweets</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th colspan="2">Message</th>
      <th>Is retweet</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td colspan="2"><%= tweet.message %></td>           
        <td><%= tweet.is_retweet %></td>        
        <td><%= link_to 'Show', tweet %></td>
        <% if can? :edit, tweet %>
          <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <% end %>
        <% if can? :destroy, tweet %>
          <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Tweet', new_tweet_path %>

 

app/views/tweets/new.html.erb
<h3 align="center">New Tweet</h3>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-8 col-md-offset-1">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag(@tweet.attachment_url, size: "110x90", class: "img-rounded") unless @tweet.attachment_url.nil? %> 
      </div>
      <div class="col-md-4">
        <%= raw @tweet.message %>
      </div>
    </div>
  </div>
</div><br>
<div class="row">
  <div class="col-md-12">
    <%= link_to 'Edit', edit_tweet_path(@tweet) if can? :destroy, @tweet %>
  </div>
</div>
<hr/>
<div class="row">
  <div class="col-md-8 col-md-offset-1">
    <div class="row">
      <div class="col-md-3" id="like-id_<%= @tweet.id%>">    
        <% if is_liked(@tweet.id) %>
          <div class= "t-pointer" onclick="likeFunction(<%= @tweet.id %>)">Like</div>
        <% else %>
          <div class= "t-pointer" onclick="dislikeFunction(<%= @tweet.id %>)">Dislike</div>
        <% end %>
      </div>
      <div class="col-md-3">
        <div onclick="addTweetId(<%= @tweet.id %>)"><a data-toggle="modal" data-target="#myModal">Comment</a></div>
      </div>
      <div class="col-md-3">
        retweet
      </div>
    </div>
  </div>
</div><br>
<div class="row">
  <div class="col-md-8 col-md-offset-1">
    <div class="row">
      <div class="col-md-3" id="total-liked">    
        <%= @total_liked.size %>
      </div>
      <div class="col-md-3">
        <%= @total_comments.size %>
      </div>
      <div class="col-md-3">
        retweet
      </div>
    </div>
  </div>
</div>



<h3>All Comments</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th colspan="3">Comments</th>      
    </tr>
  </thead>
  <tbody>
    <% @total_comments.each do |comment| %>
      <tr>
        <td colspan="3">
          <div class="row">
            <div class="col-md-10 col-md-offset-1">
              <div class="row">
                <div class="col-md-4">
                  <%= image_tag(comment.attachment_url, size: "80x65", class: "img-rounded") unless comment.attachment_url.nil? %> 
                </div>
                <div class="col-md-6">
                  <%= raw comment.message %>
                </div>
              </div>
            </div>
          </div>
        </td>        
      </tr>
    <% end %>
  </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Comment</h4>
      </div>
      <div class="modal-body">
        <%= form_for :comment, url: create_comment_comments_path, remote: true, html: {class: "comment-form"}, local: true do |form| %>
          <div class="form-group">
            <label for="message">Message Text:</label>           
            <%= form.text_area :message, id: :comment_message, class: "form-control", required: true %>
          </div>

          <div class="form-group">
            <label for="attachment">Attachment:</label>
            <%= form.file_field :attachment, id: :comment_attachment %>
          </div>

          <div class="field">    
            <%= form.hidden_field :user_id, value: current_user.id, id: :comment_user_id %>
            <%= form.hidden_field :tweet_id, id: :comment_tweet_id %>
            <%= hidden_field_tag :tags, "SHOW" %>           
          </div>
          <div class="actions">
            <%= form.submit class: "btn btn-default"%>
          </div>
        <% end %>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div> -->
    </div>
  </div>
</div>

<script type="text/javascript">
  var tLiked = <%= @total_liked.size %>
  function likeFunction(tweet) {
    $.ajax({
      url: "<%= like_likes_path %>",
      data: {"tweet_id": tweet},
      success: function(data){
        $("#like-id_" + tweet).html('<div class= "t-pointer" onclick="dislikeFunction(' + tweet + ')">Dislike</div>');
        $("#total-liked").html(parseInt(tLiked) + 1 );
        tLiked = parseInt(tLiked) + 1;
      }
    });
  }

  function dislikeFunction(tweet) {
    $.ajax({
      url: "<%= dislike_likes_path%>",
      data: {"tweet_id": tweet},
      success: function(data){
        $("#like-id_" + tweet).html('<div class= "t-pointer" onclick="likeFunction(' + tweet + ')">Like</div>');
        $("#total-liked").html(parseInt(tLiked) - 1 );
        tLiked = parseInt(tLiked) - 1;
      }
    });
  }
</script>