config/routes.rb
Rails.application.routes.draw do
	resources :tweets do
		collection do
			get 'get_user_tweets'
		end
	end

	resources :profiles

	devise_for :users

	resources :home do
		collection do
			get 'search_user'
			get 'tweets'
		end
	end

	resources :following do
		collection do
			get 'follow'
			get 'unfollow'
			get 'following_list'
			get 'followers'
		end
	end

	resources :likes do
		collection do
			get 'like'
			get 'dislike'
		end
	end

	resources :comments do
		collection do
			post 'create_comment'
		end
	end

	devise_scope :user do
		authenticated :user do
			root to: "home#index", as: :authenticated_root
		end
		unauthenticated do
			root 'devise/sessions#new', as: :unauthenticated_root
		end
	end	

  match '/*a', to: 'application#not_found', via: [:get, :post, :put, :delete]
end

app/views/layouts/_login_items.html.erb
<% if user_signed_in? %>
	<li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
	<li><%= link_to("#{current_user.email.truncate(20)}", profile_path(current_user.profile)) %></li>
<% else %>
	<li><%= link_to('Login', new_user_session_path)  %></li>
<% end %>

app/views/layouts/_registration_items.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Home', home_index_path %></li>
  <li><%= link_to('Edit registration', edit_user_registration_path) %></li>
  <li>
    <% if current_user.profile %>
      <%= link_to 'Profile', profile_path(current_user.profile) %>
    <% else %>
      <%= link_to 'Add profile', new_profile_path %>
    <% end %>
  </li>
  <li><%= link_to 'My Tweets', tweets_path %></li>
<% else %>
  <li><%= link_to('Register', new_user_registration_path)  %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Twitter</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>  
     <div class="container">
      <div class="row">
        <div class="col-lg-2">
        </div>
        <div class="col-lg-8">        
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <a class="navbar-brand" href="#">Twitter</a>
              </div>
              <ul class="nav navbar-nav">
                <%= render 'layouts/registration_items' %>
                <%= render 'layouts/login_items' %>
              </ul>
            </div>
          </nav>
          <div class="panel panel-default">
            <div class="panel-body">
              <%= yield %>
            </div>
          </div>
      </div>
      <div class="col-lg-2">
        </div> 
    </div>
  </body>
</html>
<style type="text/css">
  body {
    background-color: rgba(149, 147, 152, 0.15);
  }
  .notice, .alert {
    color: red;
  }
</style>